#!/bin/bash
#command line arguments: max_error problem
#example call ./testscript 0.01 p0

#script that runs girdl for different accuracies and outomatically creates all plots 
#and saves them to results directory
ERR=$1
PRO=$2
P1="p0"
P2="p1"

GRID_PARAM="${2:1}"
echo "grid param is $GRID_PARAM"

if [ $2 == $P1 ]; then
	#write sed argument into nex file
	echo "s/\(\\\"ImagePath\\\" *:*\).*/\\1 \"prob0MR.png\",/" > sed.text
	#call sed with file as argument
	sed -i -f sed.text config.json
	rm sed.text
	echo "s/\(\\\"AnalyticInnerRadius\\\" *:*\).*/\\1 5,/" > sed.text
	#call sed with file as argument
	sed -i -f sed.text config.json
	rm sed.text
	echo "s/\(\\\"AnalyticOuterRadius\\\" *:*\).*/\\1 96/" > sed.text
	#call sed with file as argument
	sed -i -f sed.text config.json
	rm sed.text
elif [ $2 == $P2 ]; then
	#write sed argument into nex file
	echo "s/\(\\\"ImagePath\\\" *:*\).*/\\1 \"prob1.png\",/" > sed.text
	#call sed with file as argument
	sed -i -f sed.text config.json
	rm sed.text
	echo "s/\(\\\"AnalyticInnerRadius\\\" *:*\).*/\\1 3,/" > sed.text
	#call sed with file as argument
	sed -i -f sed.text config.json
	rm sed.text
	echo "s/\(\\\"AnalyticOuterRadius\\\" *:*\).*/\\1 50/" > sed.text
	#call sed with file as argument
	sed -i -f sed.text config.json
	rm sed.text
fi


#write sed argument into nex file
echo "s/\(\\\"MaxRelErr\\\" *:*\).*/\\1$ERR,/" > sed.text
#call sed with file as argument
sed -i -f sed.text config.json
rm sed.text

#execute main programm
bin/gridle -$GRID_PARAM config.json

#run plot script
./plotscript $ERR $PRO 

